systemProp.http.proxyHost=10.10.78.61
systemProp.http.proxyPort=3128
systemProp.http.proxyUser=<entrynumber>
systemProp.http.proxyPassword=<psswrd>

systemProp.https.proxyHost=10.10.78.61
systemProp.https.proxyPort=3128
systemProp.https.proxyUser=<entry number>
systemProp.https.proxyPassword=<psswrd>

